# Generated by Django 3.0.5 on 2020-04-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(max_length=280)),
                ('tweet_polarity', models.FloatField(blank=True, null=True)),
                ('tweet_subjectivity', models.FloatField(blank=True, null=True)),
                ('tweet_sentiment', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
