# Generated by Django 3.0.5 on 2020-04-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0002_tweet_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='customer_name',
            field=models.CharField(blank=True, default='Company Name', max_length=50, null=True),
        ),
    ]
